---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-"{{ .Values.env }}"
spec:
  acme:
    server: "{{ .Values.server }}"
    email: "{{ .Values.email }}"
    privateKeySecretRef:
      name: letsencrypt-"{{ .Values.env }}"
    solvers:
      - http01:
          ingress:
            class: nginx
